# Generated by Django 4.2.23 on 2025-07-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_rag', '0002_rename_documents_document_rename_questions_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='field',
            new_name='link',
        ),
    ]
