# Generated by Django 4.2.23 on 2025-07-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_rag', '0003_rename_field_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='rag_sources/'),
        ),
        migrations.AddField(
            model_name='source',
            name='notion_db_ids',
            field=models.TextField(blank=True, help_text='Liste des IDs de bases Notion, séparés par des virgules', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
