# Generated by Django 4.2.23 on 2025-07-25 18:44

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def create_default_collection(apps, schema_editor):
    """Créer une collection par défaut"""
    Collection = apps.get_model('django_app_rag', 'Collection')
    Collection.objects.create(
        title='Collection par défaut',
        description='Collection créée automatiquement lors de la migration',
        created_at=timezone.now(),
        updated_at=timezone.now()
    )


def reverse_create_default_collection(apps, schema_editor):
    """Supprimer la collection par défaut en cas de rollback"""
    Collection = apps.get_model('django_app_rag', 'Collection')
    Collection.objects.filter(title='Collection par défaut').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_rag', '0004_source_file_source_notion_db_ids_alter_source_link'),
    ]

    operations = [
        # Créer une collection par défaut avant les autres opérations

        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(
            create_default_collection,
            reverse_create_default_collection
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='source',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='django_app_rag.collection'),
            preserve_default=False,
        ),
    ]
