# Generated by Django 4.2.23 on 2025-07-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_rag', '0005_collection_delete_document_source_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='source',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='django_app_rag.question'),
        ),
    ]
