# Generated by Django 4.2.23 on 2025-07-26 10:27

from django.db import migrations, models
import django.db.models.deletion
import django_app_rag.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_rag', '0006_remove_answer_source_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nom de la configuration RAG', max_length=255)),
                ('config_file', models.FileField(help_text='Fichier de configuration YAML pour le pipeline RAG', upload_to=django_app_rag.models.rag_config_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Configuration active pour cette collection')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_configs', to='django_app_rag.collection')),
            ],
            options={
                'verbose_name': 'Configuration RAG',
                'verbose_name_plural': 'Configurations RAG',
                'ordering': ['-created_at'],
            },
        ),
    ]
