# Generated by Django 5.0.4 on 2025-08-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_rag', '0007_ragconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='documents',
            field=models.ManyToManyField(related_name='answers', to='django_app_rag.document'),
        ),
    ]
