# Generated by Django 5.0.4 on 2025-08-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_rag', '0009_alter_answer_question_alter_document_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
