# Generated by Django 5.0.1 on 2025-09-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_rag', '0010_source_is_indexed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
