# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_rag', '0011_source_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragconfig',
            name='config_hash',
            field=models.CharField(
                blank=True,
                help_text='SHA256 hash de la configuration pour détecter les changements',
                max_length=64,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='ragconfig',
            name='version',
            field=models.IntegerField(
                default=1,
                help_text='Numéro de version de la configuration'
            ),
        ),
    ]
