collection_name: notion
load_dataset_id: notion
fetch_limit: 1000
summarization_agent_model_id: gpt-4o-mini
summarization_agent_mock: false
summarization_max_characters: 256
val_split_ratio: 0.3
test_split_ratio: 0.1
min_document_characters: 50 