data_dir: "data"
collection_name: "collection"
source_type: "file"  # file, url, notion
source_identifier: "path/to/source"
quality_agent_model_id: "gpt-4o-mini"
quality_agent_mock: true
max_workers: 10
storage_mode: "append"  # append ou overwrite
